services:
  mysql:
    image: mysql:8
    container_name: mysql-scheduler-app
    environment:
      - MYSQL_ROOT_PASSWORD=scheduler
      - MYSQL_DATABASE=scheduler
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=2000
    volumes:
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d:ro
    ports:
      - "3316:3306"