spring:
  application:
    name: scheduler-app-develop

  datasource:
    url: jdbc:mysql://localhost:3316/scheduler
    username: root
    password: scheduler
    hikari:
      maximum-pool-size: 10

  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    enabled: true
    path: /api-docs-json
  swagger-ui:
    path: /swagger-ui
    url: /api-docs-json
